theme: "hugo-PaperMod"
baseURL: http://amirfaour.netlify.app
languageCode: en-us
title: Amir Faour
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
